blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^Cadastro/$', views.Cadastro, name='Cadastro'),
	url(r'^MEUAPP/$', views.MEUAPP, name='MEUAPP'),
	url(r'^desenvolvedor/$', views.desenvolvedor, name='desenvolvedor'),
    url(r'^$', views.index, name='index'),
    url(r'^home/$', views.home, name='home'),
    url(r'^(?P<pergunta_id>[0-9]+)/$', views.detail, name='detail'),
     # ex: /polls/5/results/
    url(r'^(?P<pergunta_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<pergunta_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^blog/', include('blog.urls', namespace="blog")),
     url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

blog/models.py
from django.db import models
from django.utils import timezone

from django.db import models
from django.utils import timezone
import datetime



class Pergunta(models.Model):
    pergunta_texto=models.CharField(max_length=200)
    data=models.DateTimeField('date_published')

    def __str__(self):
        string= (str(self.pergunta_texto) + " Data: " + str(self.data))
        return string
    def Data(self):
        return self.data >= timezone.now() - datetime.timedelta(days=1)
class Reposta(models.Model):

    pergunta=models.ForeignKey(Pergunta)
    resposta_texto=models.CharField(max_length=200)
    votos=models.IntegerField(default=0)

    def __str__(self):
        return self.resposta_texto
class SignUp(models.Model):
    email=models.EmailField()
    full_name=models.CharField(max_length=40)
    timestamp=models.DateTimeField(auto_now_add=True, auto_now=False)
    update=models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.email         

blog/forms.py
from django import forms
from .models import SignUp

class SignUpForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())
	class Meta:
		model=SignUp
		fields=['email', 'full_name', 'password']

	def clean_email(self):
		email=self.cleaned_data.get('email')
		email_base, provider=email.split('@')
		domain, extension=provider.split('.')
		if not extension=='com':
			raise forms.ValidationError('Por Favor inserir Email Correto')
		return email
	def clean_full_name(self):
		#formatar depois
		full_name=self.cleaned_data.get('full_name')
		return full_name
	def __str__(self):
		return str(password)	

blog/views.py
from django.shortcuts import render, Http404, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from .models import Pergunta
from django.core.urlresolvers import reverse
from .forms import SignUpForm
from django.contrib.auth.hashers import make_password
def index(request):
    return render(request, "index.html", {});

def detail(request, pergunta_id):
    try:
        pergunta = Pergunta.objects.get(pk=pergunta_id)
    except Pergunta.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'pergunta': pergunta})
def vote(request, pergunta_id):
    p = get_object_or_404(Pergunta, pk=pergunta_id)
    try:
        selected_reposta = p.reposta_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_reposta.votos += 1
        selected_reposta.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('blog:results', args=(p.id,)))	
def results(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)
    return render(request, 'polls/results.html', {'pergunta': pergunta})
def home(request):
	Lista = Pergunta.objects.order_by('-data')[:5]
	context = {'Lista': Lista}
	return render(request, "polls/home.html", context)
def desenvolvedor(request):
    return render(request, "polls/desenvolvedor.html", {})
def MEUAPP(request):
    return render(request, "polls/MEUAPP.html", {})	
def Cadastro(request):
    title='Bem vindo Faca O Seu Cadastro'
    form=SignUpForm(request.POST or None)

    context={"MyTitle" : title,
            "form": form,
    }

    if(form.is_valid()):
        instance=form.save(commit=False)
       


       
        instance.save()

        context={"MyTitle": "Obrigado %s" %(instance.full_name),
        }

    return render(request, "polls/Cadastro.html" , context)

templates/home.html
<!DOCTYPE html>
<html>
<head>
<title>Home.html</title>
<meta charset="utf-8" />
</head>

<body>
<fieldset>
<h1>Aprendendo</h1>
{%  if  Lista  %} 
    <ul> 
    {%  for  question  in  Lista  %} 
        <li><a  href= "/blog/ {{  pergunta.id  }} /" > {{  question.pergunta_texto  }} </a></li>
    {%  endfor  %} 
    </ul> 
{%  else  %} 
    <p> Não ha nada na lista. </ p> 
{%   endif%}
</fieldset>
</body>



</html>

templates/index.html
{% extends "polls/base.html" %}
{% load staticfiles %}

<!DOCTYPE html>

<html lang="pt-br">

<head>
<title></title>
<link href=" {% static 'Css/estilo.css'%}" rel="stylesheet" />
</head>
<body>
    {% block content %}

     
        <h1>Bem Vindo (:</h1>
        <p class="lead">Olá Internautas, esse site foi criado com fins estudantis,tendo intuito de Praticar conceitos de programação web.</p>
       	{% if request.user.is_authenticated %}
       	<h1>Voce está logado (:</h1>
       	{% else %}
        <a href="Cadastro/" role="button">Cadastre-se aqui</a>
        {% endif %}
        <img src = "{% static 'Imagens/PrimeiroGif.gif' %}" />
        <h2>Trabalho Professor Fabricio! Relizando um gif</h2>
      
    {% endblock %}

  </body>

templates/polls/Cadastro.html
{% extends "polls/base.html" %}
{% load staticfiles %}


<!DOCTYPE html>


<html lang="pt-br">
<head>



<title></title>

</head>


{% block content %}

<form id="F" action"/blog/Cadastro/" method ="POST" >
{% csrf_token %}


<fieldset id="cadastro">
<legend>Cadastre-se Aqui</legend>
{{ form.as_p }}
<input type="submit" value="Salvar" id="salvar" />

</fieldset>

</form>	


{% endblock %}



</html>

templates/polls/MEUAPP.html
{% extends 'polls/base.html' %}
{% load staticfiles %}
<!DOCTYPE html>

<html lang="pt-br">
<head>
<meta charset="utf-8" />
<title></title>
<script type="text/javascript" src="{% static 'script/baladinha.js '%}"></script>
</head>
<body>



{% block content %}

<img src="" />
<img src="" />
<img src="" />
<img src="" />
<img src="" />
<img src="" />
<img src="" />
<img src="" />
<img src="" />
<img src="" />


{% endblock%}

</div>

</body>
</html>

templates/polls/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt-br"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<title></title>
<meta charset="UTF-8">
<link href="{% static 'Css/estilo.css' %}" rel="stylesheet">
<link href="{% static 'Css/formulario.css' %}" rel="stylesheet">
</head>
<body>


<div id="inter">
<header id="cabeca">
<nav id="menu">
<ul>
	<li><a href="/blog/">Inicio</a> </li>
	{% if request.user.is_authenticated %}
	<li><a href="">logout</a> </li>
	{% else %}
	<li><a href="/blog/Cadastro"> Cadastre-se</a></li>
	{% endif %}
	<li id="h"><a href="#"> Meus Apps</a>
		<ul>
			<li><a href="/blog/MEUAPP/">Cine</a></li>
			<li><a href="#">Votacao</a></li>
			<li><a href="#">etc</a></li>
		</ul>
	</li>
</ul>
</nav>
</header>

<section id="secao1">
<h1 id="fabrica">Aprendendo Conceitos Web</h1>
</section>

<section id="secao">
{% block content %}
{% endblock %}

</section>
<section id="divisor" >
<h1></h1>
</section>

<footer id="rodape">
<ul>
<li><p>Por Phablo Vilas Boas</p></li>
<li><a href="https://www.facebook.com"> Facebook </a></li>
<li><a href="https://www.twiter.com"> twiter </li>
<li><a href="/blog/desenvolvedor/"> Fale Conosco </a> </li>
<ul>
</footer>


</div>





</body></html>

templates/polls/desenvolvedor.html
{% extends 'polls/base.html' %}
{% load staticfiles %}
<!DOCTYPE html>

<html>
<head>
<title></title>
<meta charset="UTF-8" />


<link href=" {% static 'Css/style.css'%}" rel="stylesheet" />


</head>

<body>

<div id="Interface">
<header id="block">



{% block content %}
	<H1>Phablo Vilas Boas</H1>
	<img src="{%static 'Imagens/phablo.jpg' %}" />
{% endblock %}

</div>
</body>
</html>

templates/polls/detail.html
{% load staticfiles %}
<!DOCTYPE html>

<html>
<head>
<title></title>
<meta charset="utf-8"/>
<link href="{%static 'Css/style.css' %}" rel="stylesheet" />
</head>
<body>
<fieldset>	
<h1>{{pergunta.pergunta_texto}}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p> {% endif %}
<form action="{% url 'blog:vote' pergunta.id %}" method="post">
{% csrf_token %}

{% for choice in pergunta.reposta_set.all %}
<input type="radio" name="choice" id="choice{{fooloop.counter }}" value="{{choice.id}}"/>

<label for="choice{{forloop.counter}}">{{choice.resposta_texto}}</label><br/>
{% endfor %}

<input type="submit" value="Vote" />
</form>

</fieldset>
</ul>

</body>
</html>

templates/polls/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<title>Home.html</title>
<meta charset="utf-8" />
<link href=" {% static 'Css/style.css'%}" rel="stylesheet" />

</head>

<body>

{% include 'polls/interface.html' %}

{%  if  Lista  %} 
    <ul> 
    {%  for  question  in  Lista  %} 
        <li><a href="{% url 'blog:detail' question.id %}"> {{  question.pergunta_texto  }} </a></li> 
    {%  endfor  %} 
    </ul> 
{%  else  %} 
    <p> Não ha nada na lista. </ p> 
{%   endif%}

</body>



</html>

templates/polls/interface.html
<div id="inter">
<header id="cabeca">
<nav id="menu">
<ul>
  <li><a href="#">Sobre</a></li>
  <li><a href="#">Cadastre-se</a></li>
  <li><a href="#">MeusAPP</a></li>
  <li><a href="#">Desenvolvedor</a></li>
</ul>
</nav>
</header>

<section id="secao1">
<h1 id="fabrica">Fabrica de programadores</h1>
</section>

templates/polls/results.html
{% extends "polls/base.html" %}
{% load staticfiles %}

<!DOCTYPE html>

<html lang="pt-br">

<head>
<title></title>
<link href=" {% static 'Css/estilo.css'%}" rel="stylesheet" />
</head>

<body>
{% block content %}
{{pergunta}}
<h1>{{ pergunta.pergunta_texto }}</h1>

<ul>
{% for choice in pergunta.reposta_set.all %}
    <li>{{ choice.resposta_texto }} -- {{ choice.votos }} vote{{ choice.votos|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'blog:detail' pergunta.id %}">Vote novamente?</a>
{% endblock %}



</body>

</html>